@baseUrl = {{$dotenv BASE_URL}}/auth
@token = Bearer {{$dotenv TOKEN}}

POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "fulano@domain.com",
  "senha": "123456789"
}

###

GET {{baseUrl}}/me HTTP/1.1
Authorization: {{token}}

