@baseUrl = {{$dotenv BASE_URL}}/estudo
@token = Bearer {{$dotenv TOKEN}}

POST {{baseUrl}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "categoriaId": 7
}

###

GET {{baseUrl}} HTTP/1.1
Authorization: {{token}}

###

GET {{baseUrl}}/proxima-questao?estudoId=1 HTTP/1.1
Authorization: {{token}}

###

POST {{baseUrl}}/resolver-questao HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "estudoId": 1,
  "questaoId": 1,
  "alternativaId": 2
}

###

POST {{baseUrl}}/avaliar-questao HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "estudoId": 1,
  "questaoId": 1,
  "nivel": "Facil",
  "qualidade": "Bom"
}

###

DELETE {{baseUrl}}?estudoId=1 HTTP/1.1
Authorization: {{token}}

