@baseUrl = {{$dotenv BASE_URL}}/estudo
@token = Bearer {{$dotenv TOKEN}}

POST {{baseUrl}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "categoriaId": 9
}

###

GET {{baseUrl}} HTTP/1.1
Authorization: {{token}}

###

# recupera o estudo completo por id
GET {{baseUrl}}/id/1 HTTP/1.1
Authorization: {{token}}

###

GET {{baseUrl}}/proxima-questao?estudoId=1 HTTP/1.1
Authorization: {{token}}


###

POST {{baseUrl}}/resolver-questao HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "estudoId": 9,
  "questaoId": 91063,
  "alternativaId": 364249
}

###

POST {{baseUrl}}/avaliar-questao HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "questaoEstudadaId": 9,
  "nivel": "Facil",
  "qualidade": "MuitoBoa"
}

###

DELETE {{baseUrl}}?estudoId=9 HTTP/1.1
Authorization: {{token}}

