### @RequestMapping("api/alternativa")
@baseUrl = {{$dotenv baseUrl}}/alternativa
@contentType = {{$dotenv contentType}}
@token = Bearer {{$dotenv token}}

### @GetMapping("questao/{id}")
GET {{ baseUrl }}/questao/2
Authorization: {{ token }}

### @PostMapping CriarAlternativaDto params)
POST {{ baseUrl }}
Content-Type: {{ contentType }}
Authorization: {{ token }}

{
    "alternativa": "alternativa3",
    "questaoId": 2 
}

### @PatchMapping("{id}") CriarAlternativaDto params)

### @DeleteMapping("{id}")