@baseUrl = http://localhost:8080/api/categorias
@contentType = application/json
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDFAZW1haWwuY29tIiwiZXhwIjoxNjgzMzM5NDU0fQ.3QVQTn0Ae7weP797feLWIQWL44sqp0WCtiJj1nkO3gsu2Vo2XH1V-Ag_9HFXKa-Zcca0-ln5nvyreSftPzSL-Q

GET {{baseUrl}}
Authorization: {{token}}

###

POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "categoria": "avancado"
}

###

PUT {{baseUrl}}/4
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "categoria": "intermediario"
}

###

DELETE {{baseUrl}}/2
Authorization: {{token}}