@baseUrl = {{$dotenv baseUrl}}/categorias
@contentType = {{$dotenv contentType}}
@token = Bearer {{$dotenv token}}

GET {{baseUrl}}?nome=
Authorization: {{token}}

###

POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "categoria": "Matematica"
}

###

POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "categoria": "Aritimetica",
    "pai": 1
  
}

###

PUT {{baseUrl}}/4
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "categoria": "Exatas"
}

###

DELETE {{baseUrl}}/2
Authorization: {{token}}