@RequestMapping("/api/estudo")
@baseUrl = {{$dotenv baseUrl}}/estudo
@contentType = {{$dotenv contentType}}
@token = Bearer {{$dotenv token}}

@estudoId = 1
@questaoId = 5

### @GetMapping
GET {{ baseUrl }}
Authorization: {{ token }}

### @PostMapping CriarEstudoReqDto params
POST {{ baseUrl }}
Content-Type: {{ contentType }}
Authorization: {{ token }}

{
    "categoria": 2
}

### @GetMapping("/{id}") 
GET {{ baseUrl }}/{{ estudoId }}
Authorization: {{ token }}

### @GetMapping("/{id}/proxima-questao")
GET {{ baseUrl }}/{{ estudoId }}/proxima-questao
Authorization: {{ token }}

### @DeleteMapping("/{id}")
DELETE  {{ baseUrl }}/{{ estudoId }}
Authorization: {{ token }}

### @PostMapping("/{estudoId}/questao/{questaoId}/resolver") AlternativaDto alternativa
POST {{ baseUrl }}/{{ estudoId }}/questao/{{ questaoId }}/resolver
Content-Type: {{ contentType }}
Authorization: {{ token }}

{
    "id": 10
}