@baseUrl = http://localhost:8000/api/perfis
@contentType = application/json
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDFAZW1haWwuY29tIiwiZXhwIjoxNjgzMzM5NDU0fQ.3QVQTn0Ae7weP797feLWIQWL44sqp0WCtiJj1nkO3gsu2Vo2XH1V-Ag_9HFXKa-Zcca0-ln5nvyreSftPzSL-Q

GET {{baseUrl}}
Authorization: {{token}}

###

POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "nome": "ROLE_PRO"
}

###

PUT {{baseUrl}}/2
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "nome": "ROLE_FREE"
}

###

DELETE {{baseUrl}}/3
Authorization: {{token}}