### @RequestMapping("api/questoes")
@baseUrl = {{$dotenv baseUrl}}/questoes
@contentType = {{$dotenv contentType}}
@token = Bearer {{$dotenv token}}

@id = 5

### @GetMapping 
GET {{ baseUrl }}
Authorization: {{ token }}

### @PostMapping QuestaoForm form
POST {{ baseUrl }}
Content-Type: {{ contentType }}
Authorization: {{ token }}

{
    "enunciado": "enunciado3"
}

### @GetMapping("{id}")
GET {{ baseUrl }}/{{ id }}
Authorization: {{ token }}

### @PostMapping("{id}/resposta") @RequestBody AlternativaDto alternativa)
POST {{ baseUrl }}/{{ id }}/responder
Content-Type: {{ contentType }}
Authorization: {{ token }}

{
    "id": 5
}

### @PutMapping("{id}/resposta") @RequestBody AlternativaDto alternativa)
POST {{ baseUrl }}/{{ id }}/resposta
Content-Type: {{ contentType }}
Authorization: {{ token }}

{
    "id": 10
}

### @PutMapping("{id}/categoria") @RequestBody CategoriaDTO categoria)
PUT {{ baseUrl }}/{{ id }}/categoria
Content-Type: {{ contentType }}
Authorization: {{ token }}
{
   "categoria": "Matematica"
}

### @PatchMapping("{id}") @RequestBody QuestaoDto questao)


### @PutMapping("{id}/categoria/remover")

### @PutMapping("{id}/alternativa") @RequestBody AlternativaDto alternativa)
### @PutMapping("{id}/categoria/{categoriaId}") @PathVariable Integer categoriaId)
### @PutMapping("{id}/alternativa/remover") @RequestBody AlternativaDto alternativa)
### @DeleteMapping("{id}")
