@baseUrl = http://localhost:8000/api/usuarios
@contentType = application/json
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDFAZW1haWwuY29tIiwiZXhwIjoxNjgzMzMyODc2fQ.qJFw3bGCXXv4vShvsUMeMcwMUgqMLYBMOWtFSZnl7bUJu_LVANkCPRodohm_JF7WTBN2dfoLBF3A-qOR96uo6A

### CADASTRO 
POST {{ baseUrl }}
Content-Type: {{ contentType }}

{
    "nome": "user01",
    "email": "user01@email.com",
    "senha": "123"
}

### LOGIN
POST {{ baseUrl }}/auth
Content-Type: {{ contentType }}

{
    "email": "user01@email.com",
    "senha": "123"
}

### INFORMACOES USUARIO LOGADO
GET {{ baseUrl }}/info
Authorization: {{ token }}

### TODOS OS USUARIOS
GET {{ baseUrl }}
Authorization: {{ token }}

### BUSCAR PELO ID
GET {{ baseUrl }}/5
Authorization: {{ token }}
