@baseUrl = http://localhost:8000/api/usuarios
@contentType = application/json
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJleHAiOjE2ODMyODA5Mjl9.apB0GgK-7cLsqJ959fKrSzzKqvn_5Jx0MGmX72Vm0T1eOz7V18k7zncftcVqjO3xmetTX8CSyh3EfhHtXMUNdQ


### CADASTRO 
POST {{ baseUrl }}
Content-Type: {{ contentType }}

{
    "nome": "admin",
    "email": "admin@email.com",
    "senha": "123"
}

### LOGIN
POST {{ baseUrl }}/auth
Content-Type: {{ contentType }}

{
    "email": "admin@email.com",
    "senha": "123"
}

### INFORMACOES USUARIO LOGADO
GET {{ baseUrl }}/info
Authorization: {{ token }}


### TODOS OS USUARIOS
GET {{ baseUrl }}
Authorization: {{ token }}

### BUSCAR PELO ID
GET {{ baseUrl }}/5
Authorization: {{ token }}
