@baseUrl = http://localhost:8000/api/usuarios
@contentType = application/json
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDFAZW1haWwuY29tIiwiZXhwIjoxNjgzMjgzNjk0fQ.kTJFRgnbkX_KPYDHMJeu1wBJmBxGA9iFh-XkMl_qLwDcB915maAL_IH-0RmRk4cadyfFoyxSJABMPObi_oxvgg


### CADASTRO 
POST {{ baseUrl }}
Content-Type: {{ contentType }}

{
    "nome": "user01",
    "email": "user01@email.com",
    "senha": "123"
}

### LOGIN
POST {{ baseUrl }}/auth
Content-Type: {{ contentType }}

{
    "email": "user01@email.com",
    "senha": "123"
}

### INFORMACOES USUARIO LOGADO
GET {{ baseUrl }}/info


### TODOS OS USUARIOS
GET {{ baseUrl }}
Authorization: {{ token }}

### BUSCAR PELO ID
GET {{ baseUrl }}/5
Authorization: {{ token }}
